In [1]:
import socket

server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_socket.bind(('0.0.0.0', 8485))
server_socket.listen(5)
print("Listening on port 8485...")
conn, addr = server_socket.accept()
print(f"Connected by {addr}")


Listening on port 8485...
Connected by ('10.0.0.49', 40866)


In [1]:
import socket
import cv2
import pickle
import struct
import numpy as np

# Server setup
host_ip = '0.0.0.0'
port = 8485

server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
server_socket.bind((host_ip, port))
server_socket.listen(5)
print(f"🟢 Listening on {host_ip}:{port}...")

conn, addr = server_socket.accept()
print(f"✅ Connected by {addr}")

data = b""
payload_size = struct.calcsize("Q")  # size of unsigned long long int (frame length header)

try:
    while True:
        while len(data) < payload_size:
            packet = conn.recv(4096)  # Receive frame length header
            if not packet:
                break
            data += packet

        if len(data) < payload_size:
            break

        packed_msg_size = data[:payload_size]
        data = data[payload_size:]
        msg_size = struct.unpack("Q", packed_msg_size)[0]

        while len(data) < msg_size:
            data += conn.recv(4096)

        frame_data = data[:msg_size]
        data = data[msg_size:]

        frame = cv2.imdecode(np.frombuffer(frame_data, dtype=np.uint8), cv2.IMREAD_COLOR)

        cv2.imshow("📷 Live Stream", frame)
        print(frame)

        if cv2.waitKey(1) == ord('q'):
            break

except Exception as e:
    print("❌ Error:", e)
finally:
    conn.close()
    cv2.destroyAllWindows()
    print("🔌 Connection closed.")


🟢 Listening on 0.0.0.0:8485...
✅ Connected by ('10.0.0.49', 51808)
[[[ 43  48  47]
  [ 43  48  47]
  [ 46  48  48]
  ...
  [ 53  59  54]
  [ 53  59  54]
  [ 52  58  53]]

 [[ 42  47  46]
  [ 42  47  46]
  [ 45  47  47]
  ...
  [ 53  59  54]
  [ 52  58  53]
  [ 52  58  53]]

 [[ 44  46  46]
  [ 44  46  46]
  [ 45  47  47]
  ...
  [ 53  59  54]
  [ 52  58  53]
  [ 51  57  52]]

 ...

 [[ 12  13  17]
  [ 13  14  18]
  [ 11  12  16]
  ...
  [ 62  74  56]
  [109 125 102]
  [109 125 101]]

 [[ 10  13  17]
  [ 10  13  17]
  [ 10  13  17]
  ...
  [ 46  58  40]
  [105 121  97]
  [111 128 101]]

 [[ 10  13  17]
  [ 10  13  17]
  [ 10  13  17]
  ...
  [ 44  56  38]
  [ 99 115  91]
  [106 123  96]]]
[[[ 44  46  47]
  [ 44  46  47]
  [ 44  46  47]
  ...
  [ 49  56  53]
  [ 49  56  51]
  [ 52  59  54]]

 [[ 43  45  46]
  [ 44  46  47]
  [ 44  46  47]
  ...
  [ 51  58  55]
  [ 51  58  53]
  [ 53  60  55]]

 [[ 44  46  47]
  [ 44  46  47]
  [ 44  46  47]
  ...
  [ 51  58  53]
  [ 52  59  54]
  [ 53  6